app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('post/<str:slug>/', views.post_page, name='post_page'),
    path('tag/<str:slug>/', views.tag_page, name='tag_page'),
    path('author/<str:slug>/', views.author_page, name='author_page'),
    path('search/', views.search_posts, name='search'),
    path('bookmark_post/<str:slug>/', views.bookmark_post, name='bookmark_post'),
    path('like_post/<str:slug>/', views.like_post, name='like_post'),
    path('about/', views.about, name='about'),
    path('accounts/register/', views.register_user, name='register'),
    path('', views.home, name='home'),
    path('all_bookmarked_post/', views.all_bookmarked_post, name='all_bookmarked_post'),
    path('all_post/', views.all_post, name='all_post'),
    path('your_post/', views.your_post, name='your_post'),
    path('liked_post/', views.liked_post, name='liked_post'),
    path('create_post/', views.create_post, name='create_post'),
    path('my_profile/', views.my_profile, name='my_profile'),
    path('recently_played/', views.recently_played, name='recently_played'),
    path('sync_steam/', views.sync_steam, name='sync_steam'),
    path('content_sync/', views.content_sync, name='content_sync'),
    path('api/genres/', views.get_genres_by_content_type, name='api_genres'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('portfolio.urls')),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        template_name='logged_out.html'
    ), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class WebsiteMeta(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    about = models.TextField()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """
    Automatically create a Profile when a new User is created
    """
    if created:
        Profile.objects.get_or_create(
            user=instance,
            defaults={
                'slug': slugify(instance.username),
            }
        )

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    """
    Save the Profile when User is saved
    """
    try:
        instance.profile.save()
    except Profile.DoesNotExist:
        pass

class ContentType(models.Model):
    """
    Predefined content types.
    NOT user-creatable, these are fixed.
    """
    CONTENT_TYPE_CHOICES = [
        ('game', 'Game'),
        ('movie', 'Movie'),
        ('tv_show', 'TV Show'),
        ('song', 'Song'),
        ('book', 'Book'),
    ]
    
    name = models.CharField(
        max_length=20,
        choices=CONTENT_TYPE_CHOICES,
        unique=True
    )
    display_name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    icon = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        help_text="Material icon name (e.g., 'gamepad', 'movie', 'music_note')"
    )
    
    class Meta:
        ordering = ['name']
        verbose_name = 'Content Type'
        verbose_name_plural = 'Content Types'
    
    def __str__(self):
        return self.display_name


class ContentGenre(models.Model):
    """
    User-creatable genres.
    Linked to a ContentType.
    Dynamically grows as users create posts.
    """
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        related_name='genres'
    )
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='created_genres'
    )
    post_count = models.IntegerField(default=0, help_text="Number of posts with this genre")
    
    class Meta:
        unique_together = ('content_type', 'slug')
        ordering = ['-post_count', 'name']
        verbose_name = 'Content Genre'
        verbose_name_plural = 'Content Genres'
        indexes = [
            models.Index(fields=['content_type', 'name']),
            models.Index(fields=['-post_count']),
        ]
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.name} ({self.content_type.display_name})"

class SteamGame(models.Model):
    """Store recently played Steam games for a user"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='steam_games')
    appid = models.IntegerField()
    name = models.CharField(max_length=255)
    playtime_2weeks = models.IntegerField(default=0, help_text="Minutes played in last 2 weeks")
    playtime_forever = models.IntegerField(default=0, help_text="Total minutes played")
    img_icon_url = models.CharField(max_length=500, blank=True, null=True)
    img_logo_url = models.CharField(max_length=500, blank=True, null=True)
    last_synced = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'appid')
        ordering = ['-playtime_2weeks']

    def __str__(self):
        return f"{self.user.username} - {self.name}"

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    avatar = models.ImageField(upload_to='profiles/avatars/', blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=200)
    steam_id = models.CharField(max_length=50, blank=True, null=True, unique=True, help_text="User's Steam ID for API integration")
    last_sync_time = models.DateTimeField(blank=True, null=True, help_text="Last time Steam games were synced")
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.user.username)
        return super(Profile, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.user.username



class Subscriber(models.Model):
    email = models.EmailField(unique=True, max_length=100)
    subscribed_at = models.DateTimeField(auto_now_add=True)

class Comments(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    website = models.URLField(blank=True, null=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.DO_NOTHING, blank=True, null=True, related_name='replies')


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.TextField(max_length=100,blank=True, null=True)
    slug = models.SlugField(unique=True, max_length=100)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        return super(Tag, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

class Post(models.Model):

    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True, max_length=200)
    image = models.ImageField(upload_to='posts/images/', null=True, blank=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    view_count = models.PositiveIntegerField(default=0, null=True)
    is_featured = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True) 
    bookmarks = models.ManyToManyField(User, related_name='bookmarks', blank=True, default=None)
    likes = models.ManyToManyField(User, related_name='likes', blank=True, default=None)
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        help_text="Type of content this post is about"
    )
    content_genre = models.ForeignKey(
        ContentGenre,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        help_text="Genre of the content"
    )

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['author', '-created_at']),
            models.Index(fields=['content_type', 'content_genre']),
        ]   

    def __str__(self):
        return self.title
    
    def number_of_likes(self):
        return self.likes.count()
    
    def number_of_comments(self):
        return self.comments.count()

app/templates/app/about.html
{% extends 'base.html' %}
{% block title %}Blog | About{% endblock title %}
{% load static %}

{% block content %}


        <main>
    
    
    <main>
      <div class="container">
        <div class="page-top">
          <div class="top flex">
            <div class="page-name">
              <a href="{% url "app:home" %}" class="learn">
                <span class="material-icons"> keyboard_return </span> Go back
              </a>
              <h1>About</h1>
            </div>
           
          </div>
        </div>
      </div>
    </main>
    <section class="sp">
      <div class="container">
<p>{{website_info.about}}</p>
      </div>
    </section>




        </main>

{% endblock content %}

app/templates/app/all_bookmarked_post.html
{% extends 'base.html' %}
{% block title %}Blog | All bookmarked posts{% endblock title %}
{% load static %}

{% block content %}

    <main style="padding-top: 70px;">


<main>
  <div class="container">
    <div class="page-top">
      <div class="top flex">
        <div class="page-name">
          <a href="{% url "app:home" %}" class="learn">
            <span class="material-icons"> keyboard_return </span> Go back
          </a>
          <h1>All Bookmarked posts</h1>
        </div>
      </div>
    </div>
  </div>
</main>
<section class="sp">
  <div class="container">
    <div class="blog-tags">
    {% for post in posts %}
    <p class="tag">
      <a style="color: black;" href="{% url 'app:post_page' post.slug %}">{{post.title}}</a>
    </p>
    {% endfor %}
   
    
  </div>
  </div>
</section>




    </main>

 {% endblock content %}

app/templates/app/all_posts.html
{% extends 'base.html' %}
{% block title %}Blog | All posts{% endblock title %}
{% load static %}

{% block content %}

    <main style="padding-top: 70px;">


<main>
  <div class="container">
    <div class="page-top">
      <div class="top flex">
        <div class="page-name">
          <a href="{% url "app:home" %}" class="learn">
            <span class="material-icons"> keyboard_return </span> Go back
          </a>
          <h1>All Posts</h1>
        </div>
      </div>
    </div>
  </div>
</main>
<section class="sp">
  <div class="container">
    <div class="blog-tags">
    {% for post in posts %}
    <p class="tag">
      <a style="color: black;" href="{% url 'app:post_page' post.slug %}">{{post.title}}</a>
    </p>
    {% endfor %}
   
    
  </div>
  </div>
</section>




    </main>

 {% endblock content %}

app/templates/app/create_post.html
{% extends 'base.html' %}

{% block title %}Create New Post{% endblock %}

{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mb-4">Create New Post</h1>
            
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- Title Field -->
                <div class="form-group mb-3">
                    <label for="id_title" class="form-label">Post Title</label>
                    {{ form.title }}
                    {% if form.title.errors %}
                        <small class="text-danger d-block mt-2">
                            {{ form.title.errors }}
                        </small>
                    {% endif %}
                </div>
                
                <!-- Content Field -->
                <div class="form-group mb-3">
                    <label for="id_content" class="form-label">Post Content</label>
                    {{ form.content }}
                    {% if form.content.errors %}
                        <small class="text-danger d-block mt-2">
                            {{ form.content.errors }}
                        </small>
                    {% endif %}
                </div>
                
                <!-- Image Field -->
                <div class="form-group mb-3">
                    <label for="id_image" class="form-label">Featured Image</label>
                    {{ form.image }}
                    {% if form.image.errors %}
                        <small class="text-danger d-block mt-2">
                            {{ form.image.errors }}
                        </small>
                    {% endif %}
                </div>
                
                <!-- Tags Field -->
                <div class="form-group mb-3">
                    <label class="form-label">Tags</label>
                    <div class="border p-3 rounded">
                        {{ form.tags }}
                    </div>
                    {% if form.tags.errors %}
                        <small class="text-danger d-block mt-2">
                            {{ form.tags.errors }}
                        </small>
                    {% endif %}
                </div>
                
                <!-- Featured Checkbox -->
                <div class="form-check mb-3">
                    {{ form.is_featured }}
                    <label for="id_is_featured" class="form-check-label">
                        Mark as Featured Post
                    </label>
                </div>
                
                <!-- Submit Button -->
                <button type="submit" class="btn btn-secondary">
                    Create Post
                </button>
                <a href="{% url 'app:home' %}" class="btn btn-secondary">
                    Cancel
                </a>
                <script>
                    document.addEventListener('DOMContentLoaded', function() {
                        const contentTypeSelect = document.getElementById('id_content_type');
                        const contentGenreSelect = document.getElementById('id_content_genre');
                        
                        function updateGenres() {
                            const contentTypeId = contentTypeSelect.value;
                            
                            if (contentTypeId) {
                                // Fetch genres for this content type via AJAX
                                fetch(`/api/genres/?content_type=${contentTypeId}`)
                                    .then(response => response.json())
                                    .then(data => {
                                        // Clear existing options except placeholder
                                        contentGenreSelect.innerHTML = '<option value="">Select a genre...</option>';
                                        
                                        // Add new options
                                        data.genres.forEach(genre => {
                                            const option = document.createElement('option');
                                            option.value = genre.id;
                                            option.textContent = genre.name;
                                            contentGenreSelect.appendChild(option);
                                        });
                                    })
                                    .catch(error => console.error('Error:', error));
                            } else {
                                // Clear genres if no content type selected
                                contentGenreSelect.innerHTML = '<option value="">Select a content type first</option>';
                            }
                        }
                        
                        contentTypeSelect.addEventListener('change', updateGenres);
                    });
                </script>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/home.html
{% extends 'base.html' %}
{% block title %}Blog | Welcome{% endblock title %}
{% block content %}
    <main class="sp">
      <div class="container">
        <center>
          <div class="search-bar">
            <input type="text" placeholder="Search" />
            <a href="{% url 'app:search' %}" class="animated-search" onclick="searchbar()">
              <i class="uil uil-search"></i>
            </a>
          </div>
          <div class="typo">
            {% if website_info.title %}
              <h1 class="title">{{website_info.title}}</h1>
            {% else %}
              <h1 class="title">Website blog title</h1>
            {% endif %}

            {% if website_info.description %}
            <p>
              {{website_info.description}}
            </p>
            {% else %}
            <p>
              Lorem ipsum began as scrambled, nonsensical Latin derived from
              Cicero's 1st-century BC text De Finibus Bonorum et Malorum.
            </p>
            {% endif %}
          </div>
          <div class="newsletter">
            {% if request.session.subscribed == None %}
            <form method="POST">
              {% csrf_token %}
              {{subscribe_form}}
              <button class="btn btn-secondary">Subscribe</button>
            </form>
            {% endif %}
            {% if subscribe_successful %}
            <br><p>Subscribed Successfully</p>
            {% endif %}
          </div>
        </center>
      </div>
    </main>
    {% if featured_blog %}
    <section class="sp">
      <div class="container">
        <a href="{% url 'post_page' featured_blog.slug %}">
        <div class="grid-2">
          <div class="post-img">
            <img src="{{featured_blog.image.url}}" alt="" />
          </div>
          <div class="post-content">
            <div class="cetagory">
              <p>Category name</p>
            </div>
            <h1>
              {{featured_blog.title}}
            </h1>
            <p class="des">
              {{featured_blog.content|truncatechars:200}}
            </p>
            <a class="learn" href="#"
              >Learn more <span class="material-icons"> trending_flat </span></a
            >
          </div>
        </div>
      </a>
      </div>
    </section>
    {% endif %}
    <section class="sp">
      <div class="container">
        <h1 class="sec-title">Top blogs</h1>
        <div class="grid-3">
            {% for post in top_posts %}
          <!-- card -->
          <a href="{% url 'app:post_page' post.slug %}">
            <div class="card">
              <div class="post-img">
                {% if post.image %}<img src="{{post.image.url}}" alt="{{ post.title }}" />{% endif %}

                <div class="tag">{{post.tags.all.0.name}}</div>
              </div>
              <div class="card-content">
                <h3>
                  {{post.title}}
                </h3>
                <div class="author">
                  <div class="profile-pic">
                    <img src="{{post.author.profile.profile_image.url}}" alt="" />
                  </div>
                  <div class="details">
                    <p>{{post.author.first_name}}</p>
                    <small>{{post.last_updated|date}}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          <!-- card end-->
          {% endfor %}
        </div>
        <center>
          <a href="{% url "app:all_post" %}"><button class="btn btn-primary rounded view">
            View more <span class="material-icons"> trending_flat </span>
          </button></a>
        </center>
      </div>
    </section>
    <section class="sp">
      <div class="container">
        <h1 class="sec-title">New blogs</h1>
        <div class="grid-3">
            {% for post in recent_posts %}
          <!-- card -->
          <a href="{% url 'app:post_page' post.slug %}">
            <div class="card">
              <div class="post-img">
                {% if post.image %}<img src="{{post.image.url}}" alt="{{ post.title }}" />{% endif %}

                <div class="tag">{{post.tags.all.0.name}}</div>
              </div>
              <div class="card-content">
                <h3>
                  {{post.title}}
                </h3>
                <div class="author">
                  <div class="profile-pic">
                    <img src="{{post.author.profile.profile_image.url}}" alt="" />
                  </div>
                  <div class="details">
                    <p>{{post.author.first_name}}</p>
                    <small>{{post.last_updated|date}}</small>
                  </div>
                </div>
              </div>
            </div>
          </a>
          <!-- card end-->
          {% endfor %}
        </div>
        <center>
          <a href="{% url "app:all_post" %}"><button class="btn btn-primary rounded view">
            View more <span class="material-icons"> trending_flat </span>
          </button></a>
        </center>
      </div>
    </section>
    {% endblock content %}

app/templates/app/liked_post.html
{% extends 'base.html' %}
{% block title %}Blog | Liked posts{% endblock title %}
{% load static %}

{% block content %}

    <main style="padding-top: 70px;">


<main>
  <div class="container">
    <div class="page-top">
      <div class="top flex">
        <div class="page-name">
          <a href="{% url "app:home" %}" class="learn">
            <span class="material-icons"> keyboard_return </span> Go back
          </a>
          <h1>Liked Posts</h1>
        </div>
      </div>
    </div>
  </div>
</main>
<section class="sp">
  <div class="container">
    <div class="blog-tags">
    {% for post in posts %}
    <p class="tag">
      <a style="color: black;" href="{% url 'app:post_page' post.slug %}">{{post.title}}</a>
    </p>
    {% endfor %}
   
    
  </div>
  </div>
</section>




    </main>

 {% endblock content %}

app/templates/app/my_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}My Profile | The Super Blog{% endblock title %}

{% block content %}
<div class="container">
  <div class="layout">
    <!-- left layout -->
    <div class="left">
      <div class="page-top">
        <div class="top flex">
          <div class="page-name">
            <a href="{% url "app:home" %}" class="learn">
              <span class="material-icons"> keyboard_return </span> Go back
            </a>
            <h1>My Profile</h1>
          </div>
        </div>
      </div>

      <!-- Profile Header -->
      <div class="profile-header mt-4">
        <div class="profile-card">
          <div class="profile-avatar">
            {% if user.profile.avatar %}
              <img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}" class="avatar-img">
            {% else %}
              <img src="{% static 'images/author.svg' %}" alt="{{ user.username }}" class="avatar-img">
            {% endif %}
          </div>
          <div class="profile-info">
            <h2>{{ user.first_name|default:user.username }}</h2>
            <p class="username">@{{ user.username }}</p>
            {% if user.profile.bio %}
              <p class="bio">{{ user.profile.bio }}</p>
            {% endif %}
            <div class="profile-actions">
              <a href="#" class="btn btn-primary btn-sm">
                <i class="material-icons">edit</i> Edit Profile
              </a>
              <a href="{% url 'app:content_sync' %}" class="btn btn-secondary btn-sm">
                <i class="material-icons">cloud_sync</i> Content Sync
              </a>
            </div>
          </div>
        </div>
      </div>

      <!-- Tabs Navigation -->
      <div class="tabs-navigation mt-5">
        <div class="tabs-container">
          <a href="{% url 'app:your_post' %}" class="tab-link">
            <i class="material-icons">article</i> My Posts
          </a>
          <a href="{% url 'app:all_bookmarked_post' %}" class="tab-link">
            <i class="material-icons">bookmark</i> Bookmarked Posts
          </a>
          <a href="{% url 'app:liked_post' %}" class="tab-link">
            <i class="material-icons">favorite</i> Liked Posts
          </a>
          <a href="{% url 'app:recently_played' %}" class="tab-link active">
            <i class="fab fa-steam"></i> Recently Played Games
          </a>
        </div>
      </div>

      <!-- Tab Content -->
      <div class="tab-content mt-5">
        <!-- This will be replaced by the specific tab content -->
        <!-- The active tab content is loaded via the URL redirect -->
      </div>

    </div>
    <!-- left layout end -->

    <!-- right layout -->
    <div class="right">
      <div class="block">
        <h2 class="title2">Profile Stats</h2>
        <div class="stats-list">
          <div class="stat-item">
            <div class="stat-label">Total Posts</div>
            <div class="stat-value">{{ user.post_set.count }}</div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Total Bookmarks</div>
            <div class="stat-value">{{ bookmarked_posts_count }}</div>
          </div>
          <div class="stat-item">
            <div class="stat-label">Total Likes</div>
            <div class="stat-value">{{ liked_posts_count }}</div>
          </div>
        </div>
      </div>

      <div class="block">
        <h2 class="title2">Quick Links</h2>
            <div class="quick-links">
                <a href="{% url 'app:create_post' %}" class="quick-link-btn">
                    <i class="material-icons">add_circle</i> Create Post
                </a>
                <a href="{% url 'app:your_post' %}" class="quick-link-btn">
                    <i class="material-icons">list</i> View Posts
                </a>
                <a href="{% url 'app:content_sync' %}" class="quick-link-btn">
                    <i class="material-icons">cloud_sync</i> Content Sync
                </a>
                <a href="#" class="quick-link-btn">
                    <i class="material-icons">settings</i> Settings
                </a>
            </div>


      </div>

      <div class="block">
        <h2 class="title2">Account Info</h2>
        <div class="account-info">
          <p><strong>Email:</strong> {{ user.email }}</p>
          <p><strong>Member Since:</strong> {{ user.date_joined|date:"M d, Y" }}</p>
          <p><strong>Last Active:</strong> {{ user.last_login|date:"M d, Y H:i" }}</p>
        </div>
      </div>
    </div>
    <!-- right layout end -->
  </div>
</div>

<style>
  .profile-header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    padding: 30px;
    border-radius: 12px;
    color: white;
  }

  .profile-card {
    display: flex;
    gap: 20px;
    align-items: flex-start;
  }

  .profile-avatar {
    flex-shrink: 0;
  }

  .avatar-img {
    width: 120px;
    height: 120px;
    border-radius: 50%;
    border: 4px solid white;
    object-fit: cover;
  }

  .profile-info h2 {
    margin: 0;
    color: white;
    font-size: 28px;
  }

  .profile-info .username {
    color: rgba(255, 255, 255, 0.8);
    margin: 5px 0;
    font-size: 14px;
  }

  .profile-info .bio {
    margin: 10px 0;
    color: rgba(255, 255, 255, 0.9);
  }

  .profile-info .btn-sm {
    margin-top: 15px;
    background: rgba(255, 255, 255, 0.2);
    border: 2px solid white;
    color: white;
  }

  .profile-info .btn-sm:hover {
    background: white;
    color: #667eea;
  }

  .tabs-navigation {
    border-bottom: 2px solid #e0e0e0;
  }

  .tabs-container {
    display: flex;
    gap: 20px;
    flex-wrap: wrap;
  }

  .tab-link {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 12px 20px;
    text-decoration: none;
    color: #666;
    border-bottom: 3px solid transparent;
    transition: all 0.3s ease;
    font-weight: 500;
  }

  .tab-link:hover {
    color: #667eea;
  }

  .tab-link.active {
    color: #667eea;
    border-bottom-color: #667eea;
  }

  .tab-link .material-icons,
  .tab-link .fab {
    font-size: 20px;
  }

  .stats-list {
    display: grid;
    grid-template-columns: 1fr;
    gap: 15px;
  }

  .stat-item {
    padding: 15px;
    background: #f8f9fa;
    border-radius: 8px;
    border-left: 4px solid #667eea;
  }

  .stat-label {
    font-size: 12px;
    color: #666;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .stat-value {
    font-size: 28px;
    font-weight: bold;
    color: #667eea;
    margin-top: 5px;
  }

  .quick-links {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .quick-link-btn {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px 15px;
    background: #f8f9fa;
    border-radius: 8px;
    text-decoration: none;
    color: #333;
    transition: all 0.3s ease;
    border: 1px solid #e0e0e0;
  }

  .quick-link-btn:hover {
    background: #667eea;
    color: white;
    border-color: #667eea;
  }

  .quick-link-btn .material-icons {
    font-size: 20px;
  }

  .account-info {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .account-info p {
    margin: 0;
    padding: 10px;
    background: #f8f9fa;
    border-radius: 6px;
    font-size: 14px;
  }

  .account-info strong {
    color: #667eea;
  }
</style>
{% endblock content %}

app/templates/app/your_post.html
{% extends 'base.html' %}
{% block title %}Blog | Your posts{% endblock title %}
{% load static %}

{% block content %}

    <main style="padding-top: 70px;">


<main>
  <div class="container">
    <div class="page-top">
      <div class="top flex">
        <div class="page-name">
          <a href="{% url "app:home" %}" class="learn">
            <span class="material-icons"> keyboard_return </span> Go back
          </a>
          <h1>Your Posts</h1>
        </div>
      </div>
    </div>
  </div>
</main>
<section class="sp">
  <div class="container">
    <div class="blog-tags">
    {% for post in posts %}
    <p class="tag">
      <a style="color: black;" href="{% url 'app:post_page' post.slug %}">{{post.title}}</a>
    </p>
    {% endfor %}
   
    
  </div>
  </div>
</section>




    </main>

 {% endblock content %}